# Generated by Django 2.0.13 on 2019-03-02 11:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivePost',
            fields=[
                ('post_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('post_content', models.TextField()),
                ('post_image_alt_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ArchiveYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('post_id', models.UUIDField(editable=False)),
            ],
        ),
    ]
