# Generated by Django 2.0.13 on 2019-03-02 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivepost',
            name='post_summary',
            field=models.TextField(default='post summary'),
            preserve_default=False,
        ),
    ]
