# Generated by Django 2.1.5 on 2019-02-21 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0002_archiveyears'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ArchiveYears',
            new_name='ArchiveYear',
        ),
    ]
