# Generated by Django 2.1.5 on 2019-02-21 10:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0003_auto_20190221_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivepost',
            name='post_id',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='archiveyear',
            name='post_id',
            field=models.UUIDField(default='cf00625e-4121-4b17-ab70-c795d81bae10', editable=False),
            preserve_default=False,
        ),
    ]
